package utils

/*
Copyright 2022 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"fmt"
	"time"

	"github.com/gruntwork-io/terratest/modules/k8s"
	"github.com/stretchr/testify/require"
)

type App struct {
	i *Instance
}

func (a *App) StopTestApp() {
	k8s.RunKubectl(a.i.w.t, a.i.w.k8sOptions, "scale", "deploy", a.i.w.testApp.name, "--replicas=0")
	err := a.waitForAppStatus("Unhealthy", a.i.GetInfo().Host)
	require.NoError(a.i.w.t, err)
	a.i.w.testApp.isRunning = false
}

func (a *App) StartTestApp() {
	k8s.RunKubectl(a.i.w.t, a.i.w.k8sOptions, "scale", "deploy", a.i.w.testApp.name, "--replicas=1")
	err := a.waitForAppStatus("Healthy", a.i.GetInfo().Host)
	require.NoError(a.i.w.t, err)
	a.i.w.testApp.isRunning = true
}

func (a *App) waitForAppStatus(status, host string) error {
	for i := 0; i < defaultRetries; i++ {
		is, err := a.i.Resources().IngressStatus()
		if err != nil {
			return fmt.Errorf("cant read ingress status %s.%s (%s)", a.i.w.namespace, a.i.w.ingress.name, err)
		}
		a.i.w.t.Logf("Wait until ingress host %s has status %s (currently: %s)", host, status, is.HealthyRecords[host])
		if is.ServiceHealth[host] == status {
			a.i.w.t.Logf("SUCCEED: Status for %s is %s", host, status)
			return nil
		}
		time.Sleep(defaultSeconds * time.Second)
	}
	return fmt.Errorf("FAIL: Ingress has no proper status. Expect host: %s; status  %s", host, status)
}
