package assistant

/*
Copyright 2022 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"testing"

	"github.com/k8gb-io/k8gb-light/controllers/mapper"

	"github.com/stretchr/testify/assert"
)

func TestFailoverProjection(t *testing.T) {
	init := func(pg string) *mapper.LoopState {
		ls := new(mapper.LoopState)
		ls.Spec = mapper.Spec{PrimaryGeoTag: pg}
		return ls
	}
	teu := &Target{IPs: []string{"10.10.10.2", "10.10.10.3"}}
	tus := &Target{IPs: []string{"10.10.10.4", "10.10.10.5"}}
	tza := &Target{IPs: []string{"10.10.10.6", "10.10.10.7"}}
	tuk := &Target{IPs: []string{"10.10.10.8", "10.10.10.9"}}
	var tests = []struct {
		name            string
		targets         Targets
		pgs             mapper.PrimaryGeotag
		expectedTargets Targets
		expectedTag     string
	}{
		{
			name: "[us,eu,za,uk] of [eu,us,uk,za]=us", targets: Targets{"eu": teu, "us": tus, "uk": tuk, "za": tza},
			pgs:         init("us,eu,za,uk").GetFailoverOrderedGeotagList([]string{"eu", "za", "uk", "us"}),
			expectedTag: "us", expectedTargets: Targets{"us": tuk},
		},
		{
			name: "[za] of [eu,us,uk,za]=za", targets: Targets{"eu": teu, "us": tus, "uk": tuk, "za": tza},
			pgs:         init("za").GetFailoverOrderedGeotagList([]string{"eu", "za", "uk", "us"}),
			expectedTag: "za", expectedTargets: Targets{"za": tza},
		},
		{
			name: "[za,us] of [eu,us]=us", targets: Targets{"eu": teu, "us": tus},
			pgs:         init("za, us").GetFailoverOrderedGeotagList([]string{"eu", "za", "uk", "us"}),
			expectedTag: "us", expectedTargets: Targets{"us": tus},
		},
		{
			name: "[za] of [eu,us]=eu", targets: Targets{"eu": teu, "us": tus},
			pgs:         init("za").GetFailoverOrderedGeotagList([]string{"eu", "za", "uk", "us"}),
			expectedTag: "eu", expectedTargets: Targets{"eu": teu},
		},
		{
			name: "[] of [eu,us]=eu", targets: Targets{"eu": teu, "us": tus},
			pgs:         init("").GetFailoverOrderedGeotagList([]string{"eu", "za", "uk", "us"}),
			expectedTag: "eu", expectedTargets: Targets{"eu": teu},
		},
		{
			name: "[blah] of [uk,eu,us]=eu", targets: Targets{"eu": teu, "us": tus, "uk": tuk},
			pgs:         init("blah").GetFailoverOrderedGeotagList([]string{"eu", "za", "uk", "us"}),
			expectedTag: "eu", expectedTargets: Targets{"eu": teu},
		},
		{
			name: "[eu] of [uk,eu,us]={}", targets: Targets{},
			pgs:         init("eu").GetFailoverOrderedGeotagList([]string{"eu", "za", "uk", "us"}),
			expectedTag: "", expectedTargets: Targets{},
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			// arrange
			// act
			_, top := test.targets.FailoverProjection(test.pgs)
			// assert
			assert.Equal(t, test.expectedTag, top)
		})
	}
}
