package mapper

/*
Copyright 2022 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"cloud.example.com/annotation-operator/controllers/depresolver"
	"cloud.example.com/annotation-operator/controllers/providers/metrics"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

type GatewayAPIMapper struct {
	c      client.Client
	config *depresolver.Config
}

func NewGatewayAPIMapper(c client.Client, config *depresolver.Config) *GatewayAPIMapper {
	return &GatewayAPIMapper{
		c:      c,
		config: config,
	}
}

func (g GatewayAPIMapper) UpdateStatus(state *LoopState) error {
	panic("not implemented")
}

func (g GatewayAPIMapper) Get(name types.NamespacedName) (*LoopState, Result, error) {
	panic("not implemented")
}

func (g GatewayAPIMapper) GetHealthStatus(state *LoopState) (map[string]metrics.HealthStatus, error) {
	panic("not implemented")
}

func (g GatewayAPIMapper) Equal(state *LoopState, state2 *LoopState) bool {
	panic("not implemented")
}

func (g GatewayAPIMapper) TryInjectFinalizer(state *LoopState) (Result, error) {
	panic("not implemented")
}

func (g GatewayAPIMapper) TryRemoveFinalizer(state *LoopState, f func(*LoopState) error) (Result, error) {
	panic("not implemented")
}
