package mapper

/*
Copyright 2022 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"fmt"
	"testing"

	"cloud.example.com/annotation-operator/controllers/depresolver"
	"cloud.example.com/annotation-operator/controllers/utils"
	"github.com/golang/mock/gomock"
	"github.com/stretchr/testify/assert"
	netv1 "k8s.io/api/networking/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

func TestIngressMapperInjectingFinalizer(t *testing.T) {
	var serr = fmt.Errorf("update error")
	var tests = []struct {
		name               string
		expectedResult     Result
		expectedErr        error
		expectedFinalizers []string
		ingress            *netv1.Ingress
		updateError        error
	}{
		{name: "Inject Finalizer", expectedResult: ResultFinalizerInstalled, expectedErr: nil, ingress: &netv1.Ingress{},
			updateError: nil, expectedFinalizers: []string{Finalizer}},
		{name: "Inject Finalizer Between Others", expectedResult: ResultFinalizerInstalled, expectedErr: nil, updateError: nil,
			ingress:            &netv1.Ingress{ObjectMeta: metav1.ObjectMeta{Finalizers: []string{"existing", "blah"}}},
			expectedFinalizers: []string{"existing", "blah", Finalizer}},
		{name: "Finalizer Already Exists", expectedResult: ResultContinue, expectedErr: nil, updateError: nil,
			ingress:            &netv1.Ingress{ObjectMeta: metav1.ObjectMeta{Finalizers: []string{Finalizer}}},
			expectedFinalizers: []string{Finalizer}},
		{name: "Finalizer Update Error But Already Installed", expectedResult: ResultContinue, expectedErr: nil,
			ingress:            &netv1.Ingress{ObjectMeta: metav1.ObjectMeta{Finalizers: []string{Finalizer}}},
			expectedFinalizers: []string{Finalizer}, updateError: serr},
		{name: "Finalizer Update Error And Not Installed", expectedResult: ResultError, expectedErr: serr,
			ingress:            &netv1.Ingress{ObjectMeta: metav1.ObjectMeta{Finalizers: []string{}}},
			expectedFinalizers: []string{Finalizer}, updateError: serr},
		{name: "Ingress Nil", expectedResult: ResultError, expectedErr: serr, ingress: nil,
			updateError: nil, expectedFinalizers: nil},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			// arrange
			m := Client(t)
			m.Client.(*MockClient).EXPECT().Update(gomock.Any(), gomock.Any()).Return(test.updateError).Times(1)
			// act
			rs, _ := fromIngress(test.ingress, NewIngressMapper(m.Client, &depresolver.Config{}))
			result, err := rs.TryInjectFinalizer()
			// assert
			assert.Equal(t, test.expectedResult, result)
			assert.Equal(t, test.expectedErr != nil, err != nil)
			if rs.Ingress != nil {
				assert.True(t, utils.EqualItems(rs.Ingress.Finalizers, test.expectedFinalizers))
			}
		})
	}

}
