package mapper

/*
Copyright 2022 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"testing"

	"cloud.example.com/annotation-operator/controllers/utils"
	"github.com/stretchr/testify/assert"
)

func TestNewPrimaryGeoTag(t *testing.T) {
	var tests = []struct {
		name              string
		primaryGeoTag     string
		extClusterGeoTags []string
		expected          PrimaryGeotag
	}{
		{name: "US,EU from US EU ZA UK CZ", primaryGeoTag: "us, eu", extClusterGeoTags: []string{"us", "eu", "za", "uk", "cz"},
			expected: PrimaryGeotag{"us", "eu", "cz", "uk", "za"}},
		{name: "US,EU from EU US", primaryGeoTag: "us, eu", extClusterGeoTags: []string{"eu", "us"},
			expected: PrimaryGeotag{"us", "eu"}},
		{name: "US from US", primaryGeoTag: "us", extClusterGeoTags: []string{"us"},
			expected: PrimaryGeotag{"us"}},
		{name: "EMPTY of US, EU", primaryGeoTag: "", extClusterGeoTags: []string{"us", "eu"},
			expected: PrimaryGeotag{"eu", "us"}},
		{name: "ZA of US, EU", primaryGeoTag: "za", extClusterGeoTags: []string{"us", "eu"},
			expected: PrimaryGeotag{"za", "eu", "us"}},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			// arrange
			// act
			r := NewPrimaryGeotag(test.primaryGeoTag, test.extClusterGeoTags)
			// assert
			b := utils.EqualItemsHasSameOrder(test.expected, r)
			assert.True(t, b)
		})
	}
}
