package controllers

import (
	"cloud.example.com/annotation-operator/controllers/mocks"
	"cloud.example.com/annotation-operator/controllers/reconciliation"
	"context"
	"github.com/golang/mock/gomock"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"
	"testing"
)

/*
Copyright 2022 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

func TestFailoverSwitch(t *testing.T) {
	// arrange
	const ingressName = "ing"
	type result = struct {
		s   *reconciliation.LoopState
		r   reconciliation.MapperResult
		err error
	}
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()
	r := getMockedReconciler(ctrl)

	tests := []struct {
		name   string
		req    reconcile.Request
		result result
	}{
		{
			name: "Switch",
			req:  reconcile.Request{NamespacedName: types.NamespacedName{Namespace: "switch", Name: ingressName}},
			result: result{
				s:   &reconciliation.LoopState{},
				r:   reconciliation.MapperResultExists,
				err: nil},
		},
	}
	// act
	// assert
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			r.IngressMapper.(*mocks.MockMapper).EXPECT().Get(test.req.NamespacedName).
				Return(test.result.s, test.result.r, test.result.err).AnyTimes()
			_, _ = r.Reconcile(context.TODO(), test.req)
		})
	}
}
