package test

import (
	"testing"

	"github.com/k8gb-io/k8gb-light/terratest"
	"github.com/k8gb-io/k8gb-light/terratest/utils"

	"github.com/stretchr/testify/require"
)

/*
Copyright 2022 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

func TestFailoverLifecycleOnThreeClustersOrdered(t *testing.T) {
	const ingressPath1 = "./resources/ingress_fo3_ordered1.yaml"
	const ingressPath2 = "./resources/ingress_fo3_ordered2.yaml"
	const digHits = 10
	// const wgetHits = 8
	instanceEU, err := utils.NewWorkflow(t, terratest.Environment.EUCluster, terratest.Environment.EUClusterPort).
		WithIngress(ingressPath1).
		WithTestApp(terratest.Environment.EUCluster).
		WithBusybox().
		Start()
	require.NoError(t, err)
	defer instanceEU.Kill()

	instanceUS, err := utils.NewWorkflow(t, terratest.Environment.USCluster, terratest.Environment.USClusterPort).
		WithIngress(ingressPath1).
		WithTestApp(terratest.Environment.USCluster).
		WithBusybox().
		Start()
	require.NoError(t, err)
	defer instanceUS.Kill()

	instanceZA, err := utils.NewWorkflow(t, terratest.Environment.ZACluster, terratest.Environment.ZAClusterPort).
		WithIngress(ingressPath1).
		WithTestApp(terratest.Environment.ZACluster).
		WithBusybox().
		Start()
	require.NoError(t, err)
	defer instanceZA.Kill()

	t.Run("🇺🇸🇪🇺🇿🇦 Wait until EU, US, ZA clusters are ready, all targets are US", func(t *testing.T) {
		usClusterIPs := instanceUS.GetInfo().NodeIPs
		err = instanceEU.Resources().WaitUntilDNSEndpointContainsTargets(instanceEU.GetInfo().Host, usClusterIPs)
		require.NoError(t, err)
		err = instanceUS.Resources().WaitUntilDNSEndpointContainsTargets(instanceUS.GetInfo().Host, usClusterIPs)
		require.NoError(t, err)
		err = instanceZA.Resources().WaitUntilDNSEndpointContainsTargets(instanceZA.GetInfo().Host, usClusterIPs)
		require.NoError(t, err)
	})

	t.Logf("All clusters are running 🚜💨! 🇪🇺 %s;🇺🇲 %s; 🇿🇦 %s;",
		terratest.Environment.EUCluster,
		terratest.Environment.USCluster,
		terratest.Environment.ZACluster)

	t.Run("🇺🇸 Digging US,EU,ZA cluster, IPs of US are returned", func(t *testing.T) {
		usClusterIPs := instanceUS.GetInfo().NodeIPs
		ips := instanceEU.Tools().DigNCoreDNSAll(digHits)
		require.True(t, utils.MapHasOnlyKeys(ips, usClusterIPs...))
		ips = instanceUS.Tools().DigNCoreDNSAll(digHits)
		require.True(t, utils.MapHasOnlyKeys(ips, usClusterIPs...))
		ips = instanceZA.Tools().DigNCoreDNSAll(digHits)
		require.True(t, utils.MapHasOnlyKeys(ips, usClusterIPs...))
	})

	t.Run("💀🇺🇸 Killing App on Primary US cluster", func(t *testing.T) {
		zaClusterIPs := instanceZA.GetInfo().NodeIPs
		instanceUS.App().StopTestApp()
		err = instanceEU.Resources().WaitUntilDNSEndpointContainsTargets(instanceEU.GetInfo().Host, zaClusterIPs)
		require.NoError(t, err, "WARNING: If you running test locally, ensure the App with same host IS NOT running in forgotten namespaces")
		err = instanceZA.Resources().WaitUntilDNSEndpointContainsTargets(instanceZA.GetInfo().Host, zaClusterIPs)
		require.NoError(t, err, "WARNING: If you running test locally, ensure the App with same host IS NOT running in forgotten namespaces")
		err = instanceUS.Resources().WaitUntilDNSEndpointContainsTargets(instanceUS.GetInfo().Host, zaClusterIPs)
		require.NoError(t, err, "WARNING: If you running test locally, ensure the App with same host IS NOT running in forgotten namespaces")
	})

	t.Run("🇿🇦 Digging US,EU,ZA cluster, IPs of ZA are returned", func(t *testing.T) {
		zaClusterIPs := instanceZA.GetInfo().NodeIPs
		ips := instanceEU.Tools().DigNCoreDNSAll(digHits)
		require.True(t, utils.MapHasOnlyKeys(ips, zaClusterIPs...))
		ips = instanceUS.Tools().DigNCoreDNSAll(digHits)
		require.True(t, utils.MapHasOnlyKeys(ips, zaClusterIPs...))
		ips = instanceZA.Tools().DigNCoreDNSAll(digHits)
		require.True(t, utils.MapHasOnlyKeys(ips, zaClusterIPs...))
	})

	t.Run("💀🇿🇦 Killing app on Primary ZA cluster", func(t *testing.T) {
		euClusterIPs := instanceEU.GetInfo().NodeIPs
		instanceZA.App().StopTestApp()
		err = instanceEU.Resources().WaitUntilDNSEndpointContainsTargets(instanceEU.GetInfo().Host, euClusterIPs)
		require.NoError(t, err, "WARNING: If you running test locally, ensure the App with same host IS NOT running in forgotten namespaces")
		err = instanceZA.Resources().WaitUntilDNSEndpointContainsTargets(instanceZA.GetInfo().Host, euClusterIPs)
		require.NoError(t, err, "WARNING: If you running test locally, ensure the App with same host IS NOT running in forgotten namespaces")
		err = instanceUS.Resources().WaitUntilDNSEndpointContainsTargets(instanceUS.GetInfo().Host, euClusterIPs)
		require.NoError(t, err, "WARNING: If you running test locally, ensure the App with same host IS NOT running in forgotten namespaces")
	})

	t.Run("🇪🇺 Digging US,EU,ZA cluster, IPs of EU are returned", func(t *testing.T) {
		euClusterIPs := instanceEU.GetInfo().NodeIPs
		ips := instanceEU.Tools().DigNCoreDNSAll(digHits)
		require.True(t, utils.MapHasOnlyKeys(ips, euClusterIPs...))
		ips = instanceUS.Tools().DigNCoreDNSAll(digHits)
		require.True(t, utils.MapHasOnlyKeys(ips, euClusterIPs...))
		ips = instanceZA.Tools().DigNCoreDNSAll(digHits)
		require.True(t, utils.MapHasOnlyKeys(ips, euClusterIPs...))
	})

	t.Run("💀🇪🇺 Killing app on Primary EU cluster", func(t *testing.T) {
		instanceEU.App().StopTestApp()
		err = instanceEU.Resources().WaitUntilDNSEndpointContainsTargets(instanceEU.GetInfo().Host, []string{})
		require.NoError(t, err, "WARNING: If you running test locally, ensure the App with same host IS NOT running in forgotten namespaces")
		err = instanceZA.Resources().WaitUntilDNSEndpointContainsTargets(instanceZA.GetInfo().Host, []string{})
		require.NoError(t, err, "WARNING: If you running test locally, ensure the App with same host IS NOT running in forgotten namespaces")
		err = instanceUS.Resources().WaitUntilDNSEndpointContainsTargets(instanceUS.GetInfo().Host, []string{})
		require.NoError(t, err, "WARNING: If you running test locally, ensure the App with same host IS NOT running in forgotten namespaces")
	})

	t.Run("💀💀 Digging US,EU,ZA cluster, empty IPs are returned", func(t *testing.T) {
		ips := instanceEU.Tools().DigNCoreDNSAll(digHits)
		require.True(t, utils.MapHasOnlyKeys(ips))
		ips = instanceZA.Tools().DigNCoreDNSAll(digHits)
		require.True(t, utils.MapHasOnlyKeys(ips))
		r := instanceUS.Tools().DigCoreDNSHost(instanceZA.GetInfo().Host)
		require.True(t, utils.EqualItems(r, []string{}))
	})

	t.Run("🇺🇸🇪🇺🇿🇦 Reapply Ingresses", func(t *testing.T) {
		instanceEU.ReapplyIngress(ingressPath2)
		instanceUS.ReapplyIngress(ingressPath2)
		instanceZA.ReapplyIngress(ingressPath2)
		zaClusterIPs := instanceZA.GetInfo().NodeIPs
		err = instanceEU.Resources().WaitUntilDNSEndpointContainsTargets(instanceEU.GetInfo().Host, zaClusterIPs)
		require.NoError(t, err)
		err = instanceUS.Resources().WaitUntilDNSEndpointContainsTargets(instanceUS.GetInfo().Host, zaClusterIPs)
		require.NoError(t, err)
		err = instanceZA.Resources().WaitUntilDNSEndpointContainsTargets(instanceZA.GetInfo().Host, zaClusterIPs)
		require.NoError(t, err)
	})

	t.Run("🇿🇦 Digging US,EU,ZA cluster, IPs of ZA are returned", func(t *testing.T) {
		zaClusterIPs := instanceZA.GetInfo().NodeIPs
		ips := instanceEU.Tools().DigNCoreDNSAll(digHits)
		require.True(t, utils.MapHasOnlyKeys(ips, zaClusterIPs...))
		ips = instanceUS.Tools().DigNCoreDNSAll(digHits)
		require.True(t, utils.MapHasOnlyKeys(ips, zaClusterIPs...))
		ips = instanceZA.Tools().DigNCoreDNSAll(digHits)
		require.True(t, utils.MapHasOnlyKeys(ips, zaClusterIPs...))
	})

	t.Run("💀🇪🇺 Killing app on Secondary EU cluster", func(t *testing.T) {
		instanceEU.App().StopTestApp()
		zaClusterIPs := instanceZA.GetInfo().NodeIPs
		err = instanceEU.Resources().WaitUntilDNSEndpointContainsTargets(instanceEU.GetInfo().Host, zaClusterIPs)
		require.NoError(t, err, "WARNING: If you running test locally, ensure the App with same host IS NOT running in forgotten namespaces")
		err = instanceZA.Resources().WaitUntilDNSEndpointContainsTargets(instanceZA.GetInfo().Host, zaClusterIPs)
		require.NoError(t, err, "WARNING: If you running test locally, ensure the App with same host IS NOT running in forgotten namespaces")
		err = instanceUS.Resources().WaitUntilDNSEndpointContainsTargets(instanceUS.GetInfo().Host, zaClusterIPs)
		require.NoError(t, err, "WARNING: If you running test locally, ensure the App with same host IS NOT running in forgotten namespaces")
	})

	t.Run("🇿🇦 Digging US,EU,ZA cluster, IPs of ZA are returned", func(t *testing.T) {
		zaClusterIPs := instanceZA.GetInfo().NodeIPs
		ips := instanceEU.Tools().DigNCoreDNSAll(digHits)
		require.True(t, utils.MapHasOnlyKeys(ips, zaClusterIPs...))
		ips = instanceUS.Tools().DigNCoreDNSAll(digHits)
		require.True(t, utils.MapHasOnlyKeys(ips, zaClusterIPs...))
		ips = instanceZA.Tools().DigNCoreDNSAll(digHits)
		require.True(t, utils.MapHasOnlyKeys(ips, zaClusterIPs...))
	})

	t.Run("💀🇿🇦 Killing app on Primary ZA cluster", func(t *testing.T) {
		usClusterIPs := instanceUS.GetInfo().NodeIPs
		instanceZA.App().StopTestApp()
		err = instanceEU.Resources().WaitUntilDNSEndpointContainsTargets(instanceEU.GetInfo().Host, usClusterIPs)
		require.NoError(t, err, "WARNING: If you running test locally, ensure the App with same host IS NOT running in forgotten namespaces")
		err = instanceZA.Resources().WaitUntilDNSEndpointContainsTargets(instanceZA.GetInfo().Host, usClusterIPs)
		require.NoError(t, err, "WARNING: If you running test locally, ensure the App with same host IS NOT running in forgotten namespaces")
		err = instanceUS.Resources().WaitUntilDNSEndpointContainsTargets(instanceUS.GetInfo().Host, usClusterIPs)
		require.NoError(t, err, "WARNING: If you running test locally, ensure the App with same host IS NOT running in forgotten namespaces")
	})

	t.Run("🇺🇸 Digging US,EU,ZA cluster, IPs of US are returned", func(t *testing.T) {
		usClusterIPs := instanceUS.GetInfo().NodeIPs
		ips := instanceEU.Tools().DigNCoreDNSAll(digHits)
		require.True(t, utils.MapHasOnlyKeys(ips, usClusterIPs...))
		ips = instanceUS.Tools().DigNCoreDNSAll(digHits)
		require.True(t, utils.MapHasOnlyKeys(ips, usClusterIPs...))
		ips = instanceZA.Tools().DigNCoreDNSAll(digHits)
		require.True(t, utils.MapHasOnlyKeys(ips, usClusterIPs...))
	})
}
