package test

import (
	"fmt"
	"testing"

	"github.com/k8gb-io/k8gb-light/terratest"
	"github.com/k8gb-io/k8gb-light/terratest/utils"
	"github.com/stretchr/testify/require"
)

/*
Copyright 2022 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

func TestWeightRoundRobinLifecycleOnThreeClusters(t *testing.T) {
	const ingressPath = "./resources/ingress_wrr.yaml"
	const digHits = 700
	const shortDigHits = 10

	instanceEU, err := utils.NewWorkflow(t, terratest.Environment.EUCluster, terratest.Environment.EUClusterPort).
		WithIngress(ingressPath).
		WithTestApp(terratest.Environment.EUCluster).
		WithBusybox().
		Start()
	require.NoError(t, err)
	defer instanceEU.Kill()

	instanceUS, err := utils.NewWorkflow(t, terratest.Environment.USCluster, terratest.Environment.USClusterPort).
		WithIngress(ingressPath).
		WithTestApp(terratest.Environment.USCluster).
		WithBusybox().
		Start()
	require.NoError(t, err)
	defer instanceUS.Kill()

	instanceZA, err := utils.NewWorkflow(t, terratest.Environment.ZACluster, terratest.Environment.ZAClusterPort).
		WithIngress(ingressPath).
		WithTestApp(terratest.Environment.ZACluster).
		WithBusybox().
		Start()
	require.NoError(t, err)
	defer instanceZA.Kill()

	allClusterIPs := utils.Merge(instanceEU.GetInfo().NodeIPs, instanceUS.GetInfo().NodeIPs, instanceZA.GetInfo().NodeIPs)
	t.Run("Wait until EU, US, ZA clusters are ready", func(t *testing.T) {
		// waiting until all localDNSEndpoints has all addresses
		err = instanceEU.Resources().WaitUntilDNSEndpointContainsTargets(instanceEU.GetInfo().Host, allClusterIPs)
		require.NoError(t, err)
		err = instanceUS.Resources().WaitUntilDNSEndpointContainsTargets(instanceUS.GetInfo().Host, allClusterIPs)
		require.NoError(t, err)
		err = instanceZA.Resources().WaitUntilDNSEndpointContainsTargets(instanceZA.GetInfo().Host, allClusterIPs)
		require.NoError(t, err)
	})

	t.Logf("All clusters are running 🚜💨! \n🇪🇺 %s;\n🇺🇲 %s;\n🇿🇦 %s",
		terratest.Environment.EUCluster,
		terratest.Environment.USCluster,
		terratest.Environment.ZACluster)

	t.Run("🇪🇺🇺🇲🇿🇦 Digging one cluster, returned IPs of EU,US,ZA with the same probability", func(t *testing.T) {
		// "eu":4,"us":5,"za":2
		ips := instanceEU.Tools().DigNCoreDNS(digHits)
		peu := ips.HasExpectedProbabilityWithPrecision(instanceEU, 40, 10)
		pus := ips.HasExpectedProbabilityWithPrecision(instanceUS, 50, 10)
		pza := ips.HasExpectedProbabilityWithPrecision(instanceZA, 20, 10)
		require.True(t, peu)
		require.True(t, pus)
		require.True(t, pza)
		require.True(t, utils.MapHasOnlyKeys(ips, allClusterIPs...), fmt.Sprintf("expecting '%v', returned '%v'", allClusterIPs, ips))
	})

	allClusterIPs = utils.Merge(instanceEU.GetInfo().NodeIPs, instanceZA.GetInfo().NodeIPs)
	t.Run("💀🇺🇸 Killing US App, US ingress status is Unhealthy", func(t *testing.T) {
		instanceUS.App().StopTestApp()
		// waiting until all localDNSEndpoints has all addresses
		err = instanceEU.Resources().WaitUntilDNSEndpointContainsTargets(instanceEU.GetInfo().Host, allClusterIPs)
		require.NoError(t, err)
		err = instanceUS.Resources().WaitUntilDNSEndpointContainsTargets(instanceUS.GetInfo().Host, allClusterIPs)
		require.NoError(t, err)
		err = instanceZA.Resources().WaitUntilDNSEndpointContainsTargets(instanceZA.GetInfo().Host, allClusterIPs)
		require.NoError(t, err)
	})

	t.Run("🇪🇺🇿🇦 Digging one cluster, returned IPs of EU, ZA", func(t *testing.T) {
		// "eu":4,"us":5,"za":2
		ips := instanceUS.Tools().DigNCoreDNS(digHits)
		peu := ips.HasExpectedProbabilityWithPrecision(instanceEU, 65, 10)
		pza := ips.HasExpectedProbabilityWithPrecision(instanceZA, 35, 10)
		require.True(t, peu)
		require.True(t, pza)
		require.True(t, utils.MapHasOnlyKeys(ips, allClusterIPs...), fmt.Sprintf("expecting '%v', returned '%v'", allClusterIPs, ips))
	})

	allClusterIPs = instanceEU.GetInfo().NodeIPs
	t.Run("💀🇿🇦 Killing ZA App, ZA ingress status is Unhealthy", func(t *testing.T) {
		instanceZA.App().StopTestApp()
		// waiting until all localDNSEndpoints has all addresses
		err = instanceEU.Resources().WaitUntilDNSEndpointContainsTargets(instanceEU.GetInfo().Host, allClusterIPs)
		require.NoError(t, err)
		err = instanceUS.Resources().WaitUntilDNSEndpointContainsTargets(instanceUS.GetInfo().Host, allClusterIPs)
		require.NoError(t, err)
		err = instanceZA.Resources().WaitUntilDNSEndpointContainsTargets(instanceZA.GetInfo().Host, allClusterIPs)
		require.NoError(t, err)
	})

	t.Run("🇪🇺 Digging one cluster, returned IPs of EU", func(t *testing.T) {
		ips := instanceZA.Tools().DigNCoreDNS(shortDigHits)
		require.True(t, utils.MapHasOnlyKeys(ips, allClusterIPs...), fmt.Sprintf("expecting '%v', returned '%v'", allClusterIPs, ips))
	})

	allClusterIPs = []string{}
	t.Run("💀🇪🇺 Killing EU App, EU ingress status is Unhealthy", func(t *testing.T) {
		instanceEU.App().StopTestApp()
		// waiting until all localDNSEndpoints has all addresses
		err = instanceEU.Resources().WaitUntilDNSEndpointContainsTargets(instanceEU.GetInfo().Host, allClusterIPs)
		require.NoError(t, err)
		err = instanceUS.Resources().WaitUntilDNSEndpointContainsTargets(instanceUS.GetInfo().Host, allClusterIPs)
		require.NoError(t, err)
		err = instanceZA.Resources().WaitUntilDNSEndpointContainsTargets(instanceZA.GetInfo().Host, allClusterIPs)
		require.NoError(t, err)
	})

	t.Run("💀💀 Digging all clusters, returns empty lists", func(t *testing.T) {
		ips := instanceEU.Tools().DigNCoreDNS(shortDigHits)
		require.True(t, utils.MapHasOnlyKeys(ips, allClusterIPs...))
		ips = instanceUS.Tools().DigNCoreDNS(shortDigHits)
		require.True(t, utils.MapHasOnlyKeys(ips, allClusterIPs...))
		ips = instanceZA.Tools().DigNCoreDNS(shortDigHits)
		require.True(t, utils.MapHasOnlyKeys(ips, allClusterIPs...))
	})
}
