package terratest

/*
Copyright 2022 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"testing"

	"github.com/kuritka/annotation-operator/terratest/utils"

	"github.com/stretchr/testify/assert"
)

const ContextEU = "k3d-k8gb-test-eu"
const PortEU = 5053

func TestIngressCreatesDNSEndpoint(t *testing.T) {
	const ingressPath = "./resources/ingress_rr.yaml"
	instanceEU, err := utils.NewWorkflow(t, ContextEU, PortEU).
		WithIngress(ingressPath).
		WithTestApp("eu").
		Start()
	assert.NoError(t, err)
	defer instanceEU.Kill()
	expectedIPs := instanceEU.GetNodesIPs()
	host := instanceEU.Resources().Ingress().Spec.Rules[0].Host
	err = instanceEU.Resources().GetLocalDNSEndpoint().WaitUntilEndpointHasTargets(host, expectedIPs)
	assert.NoError(t, err)
}

func TestIngressRemovesDNSEndpoint(t *testing.T) {
	const ingressPath = "./resources/ingress_rr.yaml"
	instanceEU, err := utils.NewWorkflow(t, ContextEU, PortEU).
		WithIngress(ingressPath).
		WithTestApp("eu").
		Start()
	assert.NoError(t, err)
	defer instanceEU.Kill()
	expectedIPs := instanceEU.GetNodesIPs()
	host := instanceEU.Resources().Ingress().Spec.Rules[0].Host
	err = instanceEU.Resources().GetLocalDNSEndpoint().WaitUntilEndpointHasTargets(host, expectedIPs)
	assert.NoError(t, err)
}
