package dns

/*
Copyright 2022 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"fmt"

	"github.com/k8gb-io/k8gb-light/controllers/depresolver"
	"github.com/k8gb-io/k8gb-light/controllers/providers/assistant"
	"github.com/k8gb-io/k8gb-light/controllers/providers/metrics"

	"github.com/rs/zerolog"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

type ProviderFactory struct {
	config  depresolver.Config
	client  client.Client
	log     *zerolog.Logger
	metrics metrics.Metrics
}

func NewDNSProviderFactory(
	client client.Client,
	config depresolver.Config,
	log *zerolog.Logger,
	metrics metrics.Metrics,
) (f *ProviderFactory, err error) {
	if client == nil {
		err = fmt.Errorf("nil client")
	}
	if log == nil {
		err = fmt.Errorf("nil log")
	}
	if metrics == nil {
		err = fmt.Errorf("nil metrics")
	}
	f = &ProviderFactory{
		config:  config,
		client:  client,
		log:     log,
		metrics: metrics,
	}
	return
}

func (f *ProviderFactory) Provider() Provider {
	a := assistant.NewGslbAssistant(f.client, f.config.K8gbNamespace, f.config.EdgeDNSServers)
	switch f.config.EdgeDNSType {
	case depresolver.DNSTypeExternal:
		return NewExternalDNS(f.config, a, f.log)
	case depresolver.DNSTypeInfoblox:
		ibx := NewInfobloxClient(f.config)
		return NewInfobloxDNS(f.config, a, ibx, f.log, f.metrics)
	}
	return NewEmptyDNS(f.config, a)
}
