package metrics

/*
Copyright 2022 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"time"

	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/external-dns/endpoint"
)

const (
	K8gbGslbErrorsTotal               = "k8gb_gslb_errors_total"
	K8gbGslbHealthyRecords            = "k8gb_gslb_healthy_records"
	K8gbGslbReconciliationLoopsTotal  = "k8gb_gslb_reconciliation_loops_total"
	K8gbGslbServiceStatusNum          = "k8gb_gslb_service_status_num"
	K8gbGslbStatusCountForFailover    = "k8gb_gslb_status_count_for_failover"
	K8gbGslbStatusCountForRoundrobin  = "k8gb_gslb_status_count_for_roundrobin"
	K8gbGslbStatusCountForGeoIP       = "k8gb_gslb_status_count_for_geoip"
	K8gbInfobloxHeartbeatsTotal       = "k8gb_infoblox_heartbeats_total"
	K8gbInfobloxHeartbeatErrorsTotal  = "k8gb_infoblox_heartbeat_errors_total"
	K8gbInfobloxRequestDuration       = "k8gb_infoblox_request_duration"
	K8gbInfobloxZoneUpdatesTotal      = "k8gb_infoblox_zone_updates_total"
	K8gbInfobloxZoneUpdateErrorsTotal = "k8gb_infoblox_zone_update_errors_total"
	K8gbEndpointStatusNum             = "k8gb_endpoint_status_num"
	K8gbRuntimeInfo                   = "k8gb_runtime_info"
)

type Metrics interface {
	Get(name string) (r *MetricResult)
	UpdateIngressHostsPerStatusMetric(
		n types.NamespacedName,
		serviceHealth map[string]HealthStatus,
	)
	UpdateHealthyRecordsMetric(n types.NamespacedName, healthyRecords map[string][]string)
	UpdateEndpointStatus(ep *endpoint.DNSEndpoint)
	UpdateFailoverStatus(
		n types.NamespacedName,
		isPrimary bool,
		healthy HealthStatus,
		targets []string,
	)
	UpdateRoundrobinStatus(n types.NamespacedName, healthy HealthStatus, targets []string)
	UpdateGeoIPStatus(n types.NamespacedName, healthy HealthStatus, targets []string)
	IncrementError(n types.NamespacedName)
	IncrementReconciliation(n types.NamespacedName)
	InfobloxIncrementZoneUpdate(n types.NamespacedName)
	InfobloxIncrementZoneUpdateError(n types.NamespacedName)
	InfobloxIncrementHeartbeat(n types.NamespacedName)
	InfobloxIncrementHeartbeatError(n types.NamespacedName)
	InfobloxObserveRequestDuration(start time.Time, request DNSProviderRequest, success bool)
	SetRuntimeInfo(version, commit string)
	Register() (err error)
	Unregister()
}
