# Copyright 2022 The k8gb Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
# MAKEIN ?=make -C .

NGINX_INGRESS_VALUES_PATH ?= $(TERRATEST_DIR)/deploy/ingress/nginx-ingress-values.yaml
CLUSTER_GSLB_NETWORK = k3d-action-bridge-network
CLUSTER_GSLB_GATEWAY = docker network inspect $(CLUSTER_GSLB_NETWORK) -f '{{ (index .IPAM.Config 0).Gateway }}'

clean-namespaces:
	kubectl get namespace --no-headers=true -o custom-columns=NAME:metadata.name --context=k3d-k8gb-test-eu  | grep k8gb-test | xargs kubectl delete ns --context=k3d-k8gb-test-eu
	kubectl get namespace --no-headers=true -o custom-columns=NAME:metadata.name --context=k3d-k8gb-test-us  | grep k8gb-test | xargs kubectl delete ns --context=k3d-k8gb-test-us
	kubectl get namespace --no-headers=true -o custom-columns=NAME:metadata.name --context=k3d-k8gb-test-za  | grep k8gb-test | xargs kubectl delete ns --context=k3d-k8gb-test-za

terra-test:
	cd $(TERRATEST_DIR) && go mod tidy && go test $(TERRATEST_DIR)/test/ -v -timeout 40m

