name: Terratest Matrix
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  terratest:
    name: terratest-matrix
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Clusters
        uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f
        with:
          go-version: 1.19.1

      - name: Create edgeDNS k3s Cluster
        uses: AbsaOSS/k3d-action@b176c2a6dcae72e3e64e3e4d61751904ec314002
        with:
          cluster-name: "edge-dns"
          args: -c terratest/deploy/k3d/edge-dns.yaml

      - name: Create Cluster Kubernetes v1.26.0
        uses: AbsaOSS/k3d-action@b176c2a6dcae72e3e64e3e4d61751904ec314002
        with:
          cluster-name: "k8gb-test-eu"
          args: >-
            -c terratest/deploy/k3d/k8gb-test-eu.yaml
            --image docker.io/rancher/k3s:v1.20.4-k3s1

#      - name: K8GB deployment
#        run: |
#          make deploy-full-terratest-setup
#
#      - name: Running Terratests against 1 cluster
#        run: |
#         make terratest-1
